import { createStyles, makeStyles } from '@material-ui/core/styles';

export const getStyles = makeStyles(theme =>
  createStyles({
    root: {
      height: 430,
      [theme.breakpoints.down('md')]: {
        height: 385,
      },
      width: '100%',
    },
    rounded: {
      border: '2px solid rgba(91, 57, 155, 0.2)',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      '&:hover': {
        background: '#7C61AF',
      },
    },
    hoverItem: {
      color: '#ffffff',
      fontWeight: 'bold',
      fontSize: '16px',
      lineHeight: '21px',
      textTransform: 'uppercase',
      [theme.breakpoints.down('md')]: {
        fontSize: '14px',
      },
    },
    gitlab: {
      position: 'absolute',
      left: 0,
      top: '20%',
      width: 91,
      height: 91,
      [theme.breakpoints.down('sm')]: {
        width: 60,
        height: 60,
      },
    },
    js: {
      position: 'absolute',
      left: '3%',
      bottom: '20%',
      width: 53,
      height: 53,
    },
    python: {
      position: 'absolute',
      left: '15%',
      top: 0,
      width: 91,
      height: 91,
      [theme.breakpoints.down('sm')]: {
        width: 45,
        height: 45,
      },
    },
    django: {
      position: 'absolute',
      left: '15%',
      top: '45%',
      width: 67,
      height: 67,
      [theme.breakpoints.down('sm')]: {
        left: '5%',
        top: '40%',
      },
    },
    mysql: {
      position: 'absolute',
      left: '18%',
      bottom: '3%',
      width: 90,
      height: 90,
      [theme.breakpoints.down('sm')]: {
        width: 60,
        height: 60,
        left: '13%',
      },
    },
    oracle: {
      position: 'absolute',
      left: '30%',
      top: '5%',
      width: 100,
      height: 100,
      [theme.breakpoints.down('sm')]: {
        width: 50,
        height: 50,
        top: '10%',
      },
    },
    bootstrap: {
      position: 'absolute',
      left: '30%',
      top: '55%',
      width: 59,
      height: 59,
    },
    cat: {
      position: 'absolute',
      left: '41%',
      top: '30%',
      width: 50,
      height: 50,
      [theme.breakpoints.down('sm')]: {
        left: '26%',
        top: '26%',
      },
    },
    html5: {
      position: 'absolute',
      left: '40%',
      bottom: '5%',
      width: 81,
      height: 81,
      [theme.breakpoints.down('sm')]: {
        width: 55,
        height: 55,
        left: '36%',
      },
    },
    postgresql: {
      position: 'absolute',
      left: '48%',
      top: '40%',
      width: 91,
      height: 91,
      [theme.breakpoints.down('sm')]: {
        width: 50,
        height: 50,
        left: '40%',
      },
    },
    material: {
      position: 'absolute',
      left: '52%',
      top: 0,
      width: 74,
      height: 74,
    },
    php: {
      position: 'absolute',
      left: '55%',
      bottom: 0,
      width: 110,
      height: 110,
      [theme.breakpoints.down('sm')]: {
        width: 55,
        height: 55,
      },
    },
    kubernetes: {
      position: 'absolute',
      right: '26%',
      top: '50%',
      width: 74,
      height: 74,
      [theme.breakpoints.down('sm')]: {
        width: 60,
        height: 60,
      },
    },
    react: {
      position: 'absolute',
      right: '25%',
      top: '5%',
      width: 59,
      height: 59,
      [theme.breakpoints.down('sm')]: {
        right: '25%',
        top: '23%',
      },
    },
    laravel: {
      position: 'absolute',
      right: '15%',
      top: '35%',
      width: 81,
      height: 81,
      [theme.breakpoints.down('sm')]: {
        width: 40,
        height: 40,
        right: '5%',
        top: '35%',
      },
    },
    nix: {
      position: 'absolute',
      right: '15%',
      bottom: '10%',
      width: 81,
      height: 81,
      [theme.breakpoints.down('sm')]: {
        width: 65,
        height: 65,
        bottom: '16%',
        right: '25%',
      },
    },
    docker: {
      position: 'absolute',
      right: '6%',
      top: '5%',
      width: 91,
      height: 91,
      [theme.breakpoints.down('sm')]: {
        width: 45,
        height: 45,
        top: '15%',
      },
    },
    mariadb: {
      position: 'absolute',
      right: 0,
      top: '50%',
      width: 74,
      height: 74,
    },
    bitbucket: {
      position: 'absolute',
      right: '3%',
      bottom: '5%',
      width: 58,
      height: 58,
    },
  }),
);
