import { createStyles, makeStyles } from '@material-ui/core/styles';

export const getStyles = makeStyles(theme =>
  createStyles({
    root: {
      height: 430,
      [theme.breakpoints.down('md')]: {
        height: 385,
      },
      width: '100%',
    },
    rounded: {
      border: '2px solid rgba(91, 57, 155, 0.2)',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      '&:hover, &$active': {
        background: '#7C61AF',
      },
    },
    active: {},
    hoverItem: {
      color: '#ffffff',
      fontWeight: 'bold',
      fontSize: '14px',
      lineHeight: '21px',
      textTransform: 'uppercase',
      [theme.breakpoints.down('md')]: {
        fontSize: '12px',
      },
      [theme.breakpoints.down('sm')]: {
        fontSize: '8px',
      },
    },
    gitlab: {
      position: 'absolute',
      left: 0,
      top: '20%',
      width: 91,
      height: 91,
      padding: 18,
      [theme.breakpoints.down('sm')]: {
        width: 60,
        height: 60,
        padding: 8,
      },
    },
    js: {
      position: 'absolute',
      left: '3%',
      bottom: '20%',
      width: 53,
      height: 53,
      padding: '14px',
    },
    python: {
      position: 'absolute',
      left: '15%',
      top: 0,
      width: 91,
      height: 91,
      padding: 16,
      [theme.breakpoints.down('sm')]: {
        width: 45,
        height: 45,
        padding: 8,
      },
    },
    django: {
      position: 'absolute',
      left: '16%',
      top: '43%',
      width: 67,
      height: 67,
      padding: 16,
      [theme.breakpoints.down('sm')]: {
        left: '5%',
        top: '40%',
      },
    },
    mysql: {
      position: 'absolute',
      left: '18%',
      bottom: '3%',
      width: 90,
      height: 90,
      padding: '14px',
      [theme.breakpoints.down('sm')]: {
        width: 60,
        height: 60,
        left: '13%',
        padding: 6,
      },
    },
    oracle: {
      position: 'absolute',
      left: '33%',
      top: '10%',
      width: 100,
      height: 100,
      padding: '5px',
      [theme.breakpoints.down('sm')]: {
        width: 50,
        height: 50,
        top: '10%',
      },
    },
    bootstrap: {
      position: 'absolute',
      left: '30%',
      top: '55%',
      width: 59,
      height: 59,
      padding: '14px',
      [theme.breakpoints.down('sm')]: {
        left: '26%',
        top: '62%',
      },
    },
    cat: {
      position: 'absolute',
      left: '63%',
      top: '27%',
      width: 50,
      height: 50,
      padding: '10px',
      [theme.breakpoints.down('sm')]: {
        left: '26%',
        top: '26%',
      },
    },
    html5: {
      position: 'absolute',
      left: '40%',
      bottom: '5%',
      width: 81,
      height: 81,
      padding: 17,
      [theme.breakpoints.down('sm')]: {
        width: 55,
        height: 55,
        left: '36%',
        padding: 8,
      },
    },
    postgresql: {
      position: 'absolute',
      left: '46%',
      top: '35%',
      width: 91,
      height: 91,
      padding: 18,
      [theme.breakpoints.down('sm')]: {
        width: 50,
        height: 50,
        top: '45%',
        left: '33%',
        padding: 8,
      },
    },
    material: {
      position: 'absolute',
      left: '52%',
      top: 0,
      width: 74,
      height: 74,
      padding: 14,
    },
    php: {
      position: 'absolute',
      left: '55%',
      bottom: 0,
      width: 110,
      height: 110,
      padding: 15,
      [theme.breakpoints.down('sm')]: {
        width: 55,
        height: 55,
        padding: 4,
        left: '58%',
      },
    },
    kubernetes: {
      position: 'absolute',
      right: '26%',
      top: '50%',
      width: 74,
      height: 74,
      padding: 11,
      [theme.breakpoints.down('sm')]: {
        width: 60,
        height: 60,
        right: '27%',
        top: '44%',
      },
    },
    react: {
      position: 'absolute',
      right: '25%',
      top: '5%',
      width: 59,
      height: 59,
      padding: 7,
      [theme.breakpoints.down('sm')]: {
        right: '29%',
        top: '23%',
      },
    },
    laravel: {
      position: 'absolute',
      right: '13%',
      top: '35%',
      width: 81,
      height: 81,
      padding: 12,
      [theme.breakpoints.down('sm')]: {
        width: 40,
        height: 40,
        right: '5%',
        top: '35%',
        padding: 6,
      },
    },
    nix: {
      position: 'absolute',
      right: '15%',
      bottom: '10%',
      width: 81,
      height: 81,
      padding: 12,
      [theme.breakpoints.down('sm')]: {
        width: 65,
        height: 65,
        bottom: '19%',
        right: '28%',
      },
    },
    docker: {
      position: 'absolute',
      right: '6%',
      top: '5%',
      width: 91,
      height: 91,
      padding: 12,
      [theme.breakpoints.down('sm')]: {
        width: 45,
        height: 45,
        top: '15%',
        padding: 5,
      },
    },
    mariadb: {
      position: 'absolute',
      right: 0,
      top: '50%',
      width: 74,
      height: 74,
      padding: 14,
    },
    bitbucket: {
      position: 'absolute',
      right: '3%',
      bottom: '5%',
      width: 58,
      height: 58,
      padding: 9,
      [theme.breakpoints.down('sm')]: {
        right: '5%',
        bottom: '10%',
      },
    },
  }),
);
